### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by baumannzone** [baumannzone/busca-refugio-app#1]
- Nombre de la App: Sugerido: `BRos App`
- Listado de usuarios
- Detalle de un usuario
- Permitir al usuario notificar a los administradores a través de la web que se quiere unir al clan.
- Logo
- Como admin: CRUD de usuarios

**Comment by DevilslordBR** [comment]
Gracias!!

**Comment by DevilslordBR** [comment]
Hola!! 
No se si conoces http://www.diablo3ladder.com/ ahí hay mucha info sobre pj´s y clanes, lo que no se es si se podrá sacar de algún modo.

**Comment by baumannzone** [comment]
Yo encontré esto: http://www.diablo3ladder.com/best-players/eu-paragon-0-264969_Busca_Refugio.html

Pero veo que no se actualiza, y creo que el problema es el que hablábamos ayer, no se puede automatizar.

**Comment by DevilslordBR** [comment]
Actualmente dice que hay alrededor de 35 miembros (no se exactamente cuantos dice) para ésto es necesario que cada player se registre en http://www.diablo3ladder.com/ 
De momento somos esos... Algo que también sería interesante que pudiesemos poner en la web nuestra, las comparaciones entre pj´s... por ejemplo.

**Comment by baumannzone** [comment]
AL final es lo mismo, registro manual por usuario, y a partir de ahí ya puedes jugar con su info. Es lo que haremos nosotros.

**Comment by baumannzone** [comment]
- Nombre del listado de releases @DevilslordBR 
- Gestionar jerarquías del clan
